#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# packaging/generate-control-from-staging.sh
# Generate packaging/control.template using dpkg-shlibdeps from binaries in staging
#
# Usage:
#   packaging/generate-control-from-staging.sh <staging-dir> <install-prefix> <version> [extra-comma-separated-packages]
#
# Example:
#   packaging/generate-control-from-staging.sh "$GITHUB_WORKSPACE/staging" /usr "20251129-abc" "libbluray2,libsmbclient"

STAGING_DIR="${1:-${GITHUB_WORKSPACE:-.}/staging}"
PREFIX="${2:-/usr}"
VERSION="${3:-unknown}"
EXTRA="${4:-}"   # comma separated extras

OUT_TEMPLATE="${PWD}/packaging/control.template"

# Check for required tool
if ! command -v dpkg-shlibdeps >/dev/null 2>&1; then
  echo "ERROR: dpkg-shlibdeps not found. Please install dpkg-dev on the runner." >&2
  exit 2
fi

echo "Generating ${OUT_TEMPLATE} from staging: ${STAGING_DIR}${PREFIX}"
TMP_UNPACK="$(mktemp -d "${TMPDIR:-/tmp}/deb-unpack.XXXX")"

trap 'rm -rf "${TMP_UNPACK}"' EXIT

# copy staging into a temp dir to ensure paths exist and to avoid touching original
rsync -a --delete --links --perms --chmod=ugo=rX "${STAGING_DIR}${PREFIX}/" "${TMP_UNPACK}${PREFIX}/"

# Find candidate binaries/libraries to analyze
# We include executables and .so files under the prefix (bin, lib, lib64, sbin) — skip small text files
mapfile -t candidates < <(find "${TMP_UNPACK}${PREFIX}" \( -type f -a -perm /111 -o -name "*.so*" \) -print)

if [ ${#candidates[@]} -eq 0 ]; then
  echo "Warning: no candidate binaries/libs found in staging (${TMP_UNPACK}${PREFIX})" >&2
fi

# Run dpkg-shlibdeps on each candidate, collect results
# The output lines look like: "shlibs:Depends=libc6 (>= 2.34), libstdc++6 (>= 11), ..."
deps_set=""

for bin in "${candidates[@]}"; do
  # dpkg-shlibdeps may error for some binaries; use || true and capture stdout
  echo "Analyzing: ${bin}"
  out="$(dpkg-shlibdeps -O "${bin}" 2>/dev/null || true)"
  # extract after '=' if present
  if [[ "${out}" =~ =(.+) ]]; then
    depline="${BASH_REMATCH[1]}"
    # split by comma and add each to set-normalized list
    IFS=',' read -ra parts <<< "${depline}"
    for p in "${parts[@]}"; do
      # trim spaces
      p="$(echo "${p}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      # skip empty
      [ -z "${p}" ] && continue
      # append if not already present
      if ! echo "${deps_set}" | grep -F -x -q "${p}"; then
        deps_set="${deps_set}
${p}"
      fi
    done
  fi
done

# Normalize deps_set into a comma-separated single line
# Remove leading newline
deps_set="$(echo "${deps_set}" | sed '/^\s*$/d' | sed ':a;N;$!ba;s/\n/, /g')"

# Append user-specified extras (comma separated)
if [ -n "${EXTRA}" ]; then
  # normalize commas/spaces
  extras_norm="$(echo "${EXTRA}" | sed 's/, */, /g')"
  if [ -n "${deps_set}" ]; then
    deps_all="${deps_set}, ${extras_norm}"
  else
    deps_all="${extras_norm}"
  fi
else
  deps_all="${deps_set}"
fi

# If dpkg-shlibdeps produced nothing, fallback to a conservative set useful for Kodi X11
if [ -z "${deps_all//[[:space:],]/}" ]; then
  echo "dpkg-shlibdeps produced no deps — falling back to conservative minimal runtime list." >&2
  deps_all="libasound2, libx11-6, libgl1, libva2, libpulse0"
fi

# Write control.template
cat > "${OUT_TEMPLATE}" <<EOF
Package: kodi
Version: %VERSION%
Section: video
Priority: optional
Architecture: %ARCH%
Maintainer: Kodi Packager <noreply@example.com>
Homepage: https://kodi.tv/
Standards-Version: 4.6.0

Depends: \${misc:Depends}, ${deps_all}
Recommends: va-driver-all, vdpau-driver-all, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly
Suggests: kodi-inputstream-adaptive, kodi-inputstream-rtmp, kodi-game-libretro, libdvdcss2

Description: Kodi Media Center (auto-generated control)
 Kodi package generated by CI. This control.template was generated from the
 binaries found in staging and dpkg-shlibdeps analysis. Adjust manually if needed.
EOF

echo "Wrote ${OUT_TEMPLATE}. Please review and commit to packaging/ if satisfied."
exit 0
